// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdhaneiclrqqjqihwwuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkaGFuZWljbHJxcWpxaWh3d3V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MDQzMDQsImV4cCI6MjA1ODI4MDMwNH0.HlMGdJNCjCRe9XMe0MMWRhbiMaLAhmhqssK-FcjrlYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);